//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.17 at 03:11:28 PM GMT 
//


package com.elektrifi.xml.screeninglist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.elektrifi.xml.screeninglist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.elektrifi.xml.screeninglist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.DateOfBirthList }
     * 
     */
    public ScreeningList.ScreeningEntry.DateOfBirthList createScreeningListScreeningEntryDateOfBirthList() {
        return new ScreeningList.ScreeningEntry.DateOfBirthList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AddressList }
     * 
     */
    public ScreeningList.ScreeningEntry.AddressList createScreeningListScreeningEntryAddressList() {
        return new ScreeningList.ScreeningEntry.AddressList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.IdList }
     * 
     */
    public ScreeningList.ScreeningEntry.IdList createScreeningListScreeningEntryIdList() {
        return new ScreeningList.ScreeningEntry.IdList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.CitizenshipList.Citizenship }
     * 
     */
    public ScreeningList.ScreeningEntry.CitizenshipList.Citizenship createScreeningListScreeningEntryCitizenshipListCitizenship() {
        return new ScreeningList.ScreeningEntry.CitizenshipList.Citizenship();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem }
     * 
     */
    public ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem createScreeningListScreeningEntryDateOfBirthListDateOfBirthItem() {
        return new ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.CitizenshipList }
     * 
     */
    public ScreeningList.ScreeningEntry.CitizenshipList createScreeningListScreeningEntryCitizenshipList() {
        return new ScreeningList.ScreeningEntry.CitizenshipList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AkaList }
     * 
     */
    public ScreeningList.ScreeningEntry.AkaList createScreeningListScreeningEntryAkaList() {
        return new ScreeningList.ScreeningEntry.AkaList();
    }

    /**
     * Create an instance of {@link ScreeningList }
     * 
     */
    public ScreeningList createScreeningList() {
        return new ScreeningList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.ProgramList }
     * 
     */
    public ScreeningList.ScreeningEntry.ProgramList createScreeningListScreeningEntryProgramList() {
        return new ScreeningList.ScreeningEntry.ProgramList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry }
     * 
     */
    public ScreeningList.ScreeningEntry createScreeningListScreeningEntry() {
        return new ScreeningList.ScreeningEntry();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AkaList.Aka }
     * 
     */
    public ScreeningList.ScreeningEntry.AkaList.Aka createScreeningListScreeningEntryAkaListAka() {
        return new ScreeningList.ScreeningEntry.AkaList.Aka();
    }

    /**
     * Create an instance of {@link ScreeningList.PublshInformation }
     * 
     */
    public ScreeningList.PublshInformation createScreeningListPublshInformation() {
        return new ScreeningList.PublshInformation();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem }
     * 
     */
    public ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem createScreeningListScreeningEntryPlaceOfBirthListPlaceOfBirthItem() {
        return new ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.PlaceOfBirthList }
     * 
     */
    public ScreeningList.ScreeningEntry.PlaceOfBirthList createScreeningListScreeningEntryPlaceOfBirthList() {
        return new ScreeningList.ScreeningEntry.PlaceOfBirthList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.VesselInfo }
     * 
     */
    public ScreeningList.ScreeningEntry.VesselInfo createScreeningListScreeningEntryVesselInfo() {
        return new ScreeningList.ScreeningEntry.VesselInfo();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.IdList.Id }
     * 
     */
    public ScreeningList.ScreeningEntry.IdList.Id createScreeningListScreeningEntryIdListId() {
        return new ScreeningList.ScreeningEntry.IdList.Id();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AddressList.Address }
     * 
     */
    public ScreeningList.ScreeningEntry.AddressList.Address createScreeningListScreeningEntryAddressListAddress() {
        return new ScreeningList.ScreeningEntry.AddressList.Address();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.NationalityList.Nationality }
     * 
     */
    public ScreeningList.ScreeningEntry.NationalityList.Nationality createScreeningListScreeningEntryNationalityListNationality() {
        return new ScreeningList.ScreeningEntry.NationalityList.Nationality();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.NationalityList }
     * 
     */
    public ScreeningList.ScreeningEntry.NationalityList createScreeningListScreeningEntryNationalityList() {
        return new ScreeningList.ScreeningEntry.NationalityList();
    }

}
