//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.14 at 04:56:55 PM GMT 
//


package com.elektrifi.sanctions.beans;

public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tempuri.sdnlist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.CitizenshipList }
     * 
     */
    public ScreeningList.ScreeningEntry.CitizenshipList createScreeningListScreeningEntryCitizenshipList() {
        return new ScreeningList.ScreeningEntry.CitizenshipList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AkaList }
     * 
     */
    public ScreeningList.ScreeningEntry.AkaList createScreeningListScreeningEntryAkaList() {
        return new ScreeningList.ScreeningEntry.AkaList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.ProgramList }
     * 
     */
    public ScreeningList.ScreeningEntry.ProgramList createScreeningListScreeningEntryProgramList() {
        return new ScreeningList.ScreeningEntry.ProgramList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem }
     * 
     */
    public ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem createScreeningListScreeningEntryDateOfBirthListDateOfBirthItem() {
        return new ScreeningList.ScreeningEntry.DateOfBirthList.DateOfBirthItem();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.VesselInfo }
     * 
     */
    public ScreeningList.ScreeningEntry.VesselInfo createScreeningListScreeningEntryVesselInfo() {
        return new ScreeningList.ScreeningEntry.VesselInfo();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.NationalityList }
     * 
     */
    public ScreeningList.ScreeningEntry.NationalityList createScreeningListScreeningEntryNationalityList() {
        return new ScreeningList.ScreeningEntry.NationalityList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.IdList }
     * 
     */
    public ScreeningList.ScreeningEntry.IdList createScreeningListScreeningEntryIdList() {
        return new ScreeningList.ScreeningEntry.IdList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.IdList.Id }
     * 
     */
    public ScreeningList.ScreeningEntry.IdList.Id createScreeningListScreeningEntryIdListId() {
        return new ScreeningList.ScreeningEntry.IdList.Id();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AkaList.Aka }
     * 
     */
    public ScreeningList.ScreeningEntry.AkaList.Aka createScreeningListScreeningEntryAkaListAka() {
        return new ScreeningList.ScreeningEntry.AkaList.Aka();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.NationalityList.Nationality }
     * 
     */
    public ScreeningList.ScreeningEntry.NationalityList.Nationality createScreeningListScreeningEntryNationalityListNationality() {
        return new ScreeningList.ScreeningEntry.NationalityList.Nationality();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry }
     * 
     */
    public ScreeningList.ScreeningEntry createScreeningListScreeningEntry() {
        return new ScreeningList.ScreeningEntry();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem }
     * 
     */
    public ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem createScreeningListScreeningEntryPlaceOfBirthListPlaceOfBirthItem() {
        return new ScreeningList.ScreeningEntry.PlaceOfBirthList.PlaceOfBirthItem();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AddressList.Address }
     * 
     */
    public ScreeningList.ScreeningEntry.AddressList.Address createScreeningListScreeningEntryAddressListAddress() {
        return new ScreeningList.ScreeningEntry.AddressList.Address();
    }

    /**
     * Create an instance of {@link ScreeningList.PublshInformation }
     * 
     */
    public ScreeningList.PublshInformation createScreeningListPublshInformation() {
        return new ScreeningList.PublshInformation();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.CitizenshipList.Citizenship }
     * 
     */
    public ScreeningList.ScreeningEntry.CitizenshipList.Citizenship createScreeningListScreeningEntryCitizenshipListCitizenship() {
        return new ScreeningList.ScreeningEntry.CitizenshipList.Citizenship();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.PlaceOfBirthList }
     * 
     */
    public ScreeningList.ScreeningEntry.PlaceOfBirthList createScreeningListScreeningEntryPlaceOfBirthList() {
        return new ScreeningList.ScreeningEntry.PlaceOfBirthList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.DateOfBirthList }
     * 
     */
    public ScreeningList.ScreeningEntry.DateOfBirthList createScreeningListScreeningEntryDateOfBirthList() {
        return new ScreeningList.ScreeningEntry.DateOfBirthList();
    }

    /**
     * Create an instance of {@link ScreeningList }
     * 
     */
    public ScreeningList createScreeningList() {
        return new ScreeningList();
    }

    /**
     * Create an instance of {@link ScreeningList.ScreeningEntry.AddressList }
     * 
     */
    public ScreeningList.ScreeningEntry.AddressList createScreeningListScreeningEntryAddressList() {
        return new ScreeningList.ScreeningEntry.AddressList();
    }

}
